services:
  - type: web
    name: cryptopulse-backend
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: cryptopulse-redis
          property: connectionString
      - key: PORT
        value: 4000
      - key: COINGECKO_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://crypto-pulse-cs-375.vercel.app

  - type: redis
    name: cryptopulse-redis
    plan: free
    ipAllowList: []
